import type { Metadata } from 'next';
import '../styles/globals.css';
import Navbar from '@/components/Navbar';
import Providers from '@/components/providers';
import { Toaster } from 'sonner';

export const metadata: Metadata = {
  title: 'Française des développeuses',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Toaster richColors />
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
